- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: arubanetworks.aoscx.aoscx
  connection: arubanetworks.aoscx.aoscx
  gather_facts: False
  tasks:
  - name: Create VLAN 200 with description
    aoscx_vlan:
      vlan_id: 200
      description: This is VLAN 200
