---
- name: Configure VLAN on Aruba AOS-CX Switch
  hosts: controller
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Create VLAN 200 with description
      aoscx_vlan:
        vlan_id: 200
        description: This is VLAN 200
