- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
      aoscx_vlan:
        vlan_id: 10
        name: Management
        description: Management VLAN
      aoscx_vlan:
        vlan_id: 50
        state: delete
