- hosts: all
  collections:
    - arubanetworks.aoscx  
  gather_facts: False
  become: true 
  tasks:
    - name: Create VLAN 300 with description and name
      aoscx_vlan:
        vlan_id: 300
        name: UPLINK_VLAN
        description: This is VLAN 300
